### ISSUE TITLE
When can I see the demo?

### ISSUE THREAD

**Issue by grath10** [ezekielaquino/Marquee3000#16]
Demo would be of help for me to use this plugin, when will it be available?Thx!

**Comment by Keropon** [comment]
It already is available http://ezekielaquino.com/Marquee3000/

**Comment by grath10** [comment]
@Keropon Thx，I will close this issue.

**Comment by Hellogark** [comment]
The page is not found for the demo

**Comment by joebentaylor1995** [comment]
The website demo doesnt work
